source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxGesture_iOS_Demo' do
    platform :ios, '9.0'
    pod 'RxGesture', :path => '../'
end

target 'RxGesture_OSX_Demo' do
    platform :osx, '10.10'
    pod 'RxGesture', :path => '../'
end
